### ISSUE TITLE
App crashes on barcode-scan with VIBRATE-setting enabled

### ISSUE THREAD

**Issue by ajans** [journeyapps/zxing-android-embedded#102]
Hi there,

it seems that zxing-android-embedded has silently dropped support for its vibrate-setting?

I got this crash when scanning a barcode with vibrate enabled:

```
java.lang.SecurityException: Requires VIBRATE permission
    at android.os.Parcel.readException(Parcel.java:1546)
    at android.os.Parcel.readException(Parcel.java:1499)
    at android.os.IVibratorService$Stub$Proxy.vibrateMagnitude(IVibratorService.java:307)
    at android.os.SystemVibrator.vibrate(SystemVibrator.java:119)
    at android.os.SystemVibrator.vibrate(SystemVibrator.java:84)
    at android.os.Vibrator.vibrate(Vibrator.java:89)
    at android.os.Vibrator.vibrate(Vibrator.java:71)
    at com.google.zxing.client.android.BeepManager.playBeepSoundAndVibrate(SourceFile:72)
    at com.google.zxing.client.android.CaptureActivity.handleDecode(SourceFile:442)
    at com.google.zxing.client.android.CaptureActivityHandler.handleMessage(SourceFile:97)
    at android.os.Handler.dispatchMessage(Handler.java:102)
    at android.os.Looper.loop(Looper.java:145)
    at android.app.ActivityThread.main(ActivityThread.java:6837)
    at java.lang.reflect.Method.invoke(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:372)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
```

The commits that removed the vibrate-permission (among other permissions) are:

```
commit 354f209871d1aec61836e43f5f1314391eab1039
Author: Ralf Kistner <ralf@embarkmobile.com>
Date:   Fri Mar 20 09:46:33 2015 +0200

    Trim manifest of legacy lib.

commit e7b16bc3fea77078ed453889a0c4698a24c42058
Author: Ralf Kistner <ralf@embarkmobile.com>
Date:   Thu Mar 19 17:43:22 2015 +0200

    Manually update manifest.

commit 213a1a2ecac422c705edb5065c637bb8b37ea337
Author: Ralf Kistner <ralf@embarkmobile.com>
Date:   Thu Mar 19 17:41:02 2015 +0200

    Update zxing-android-complete to 3.2.0.
```

Why were those permissions removed but not the code that needs them (at least in the vibrate-case)?

**Comment by rkistner** [comment]
It's removed since vibrate is disabled by default, so most apps don't use it, and don't want the extra permission. You can just add the permission yourself if you need the vibrate functionality.

Either way the 2.x branch of the library is not actively supported anymore.
