### ISSUE TITLE
Nullpointer exception for cameraInstance

### ISSUE THREAD

**Issue by aaqibkhan** [journeyapps/zxing-android-embedded#108]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.journeyapps.barcodescanner.camera.CameraInstance.setSurfaceHolder(android.view.SurfaceHolder)' on a null object reference
       at com.journeyapps.barcodescanner.CameraPreview.startCameraPreview(CameraPreview.java:472)
       at com.journeyapps.barcodescanner.CameraPreview.startPreviewIfReady(CameraPreview.java:320)
       at com.journeyapps.barcodescanner.CameraPreview.access$200(CameraPreview.java:48)
       at com.journeyapps.barcodescanner.CameraPreview$1.surfaceChanged(CameraPreview.java:130)
       at android.view.SurfaceView.updateWindow(SurfaceView.java:590)
       at android.view.SurfaceView.setFrame(SurfaceView.java:300)
       at android.view.View.layout(View.java:15610)
       at com.journeyapps.barcodescanner.CameraPreview.onLayout(CameraPreview.java:337)
       at android.view.View.layout(View.java:15614)
       at android.view.ViewGroup.layout(ViewGroup.java:4968)
       at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
       at android.view.View.layout(View.java:15614)
       at android.view.ViewGroup.layout(ViewGroup.java:4968)
       at android.widget.FrameLayout.layoutChildren(FrameLayout.java:573)
       at android.widget.FrameLayout.onLayout(FrameLayout.java:508)
       at android.widget.ScrollView.onLayout(ScrollView.java:1505)
       at android.view.View.layout(View.java:15614)
       at android.view.ViewGroup.layout(ViewGroup.java:4968)
```

**Comment by rkistner** [comment]
Can you please give some more info? See [CONTRIBUTING.md](https://NOCgithub.com/journeyapps/zxing-android-embedded/blob/master/CONTRIBUTING.md).

**Comment by aaqibkhan** [comment]
@rkistner 
I am using these versions
```
compile 'com.journeyapps:zxing-android-embedded:3.0.2@aar'
compile 'com.google.zxing:core:3.2.0'
```
Device: Moto E2
Android version: 5.0.2

I am not able to reproduce the error. I have used the library many times with above version and it never crashed. Just this one time I got this error.

**Comment by aaqibkhan** [comment]
I am calling `resume()` in activity's `onResume()` and `pause()' in `onPause()`.
Using continuous decoding

**Comment by rkistner** [comment]
Thanks, I'll see if I can find the cause.

**Comment by Sebosam** [comment]
Hello, 
I think it's because rotation. When u rotate on clean android cameraPreview started faster before finishing stopPreview and then u have only black screen and bug:). It crashed probably in CameraSurface#setPreview. When u minimize app and take it back it start working.
Sorry for language:)

**Comment by aaqibkhan** [comment]
any progress on this?

**Comment by rkistner** [comment]
Sorry, no progress yet. Will see if I can do something before the next release.

**Comment by matyj** [comment]
any tips or workaround? it's very important for me right now, lib is good but unuseful with this error ;<

**Comment by Sebosam** [comment]
I just inject other activity onPause it isnt pretty but works for me. E.g
touch to Wake up;)

**Comment by matyj** [comment]
@Sebosam , what do you mean? i don't understand you at all. in which on pause? what injection do you mean?

**Comment by Sebosam** [comment]
@matyj Make a second activity to reset ur captureActivty. When u call onPause in captureActivity start the second activity to reset zxing camera and come back to it  onTouch event for example(like touch to wake up).

**Comment by rkistner** [comment]
@matyj Can you give more details on how you reproduce this issue and what exactly happens? My initial impression was that this issue was fairly rare and low-impact.

I'm working on a potential fix now, should have it ready soon.
