### ISSUE TITLE
Can only use lower 8 bits for requestCode when requestPermissions

### ISSUE THREAD

**Issue by hoffergg** [journeyapps/zxing-android-embedded#117]
CAMERA_PERMISSION_REQUEST = 89433; at file CaptureManager.java is too big.it should be lower than 255 which is lower 8 bits

**Comment by rkistner** [comment]
Do you have any documentation or stacktraces on that? In my tests this appeared to work, but I have seen some references to 16 bits (65535) maximum (still to big, so will change it).

**Comment by ymenager** [comment]
I can confirm that on nexus 7 with API 23

     Caused by: java.lang.IllegalArgumentException: Can only use lower 8 bits for requestCode
            at android.support.v4.app.FragmentActivity.validateRequestPermissionsRequestCode(FragmentActivity.java:763)
            at android.support.v4.app.ActivityCompatApi23.requestPermissions(ActivityCompat23.java:29)
            at android.support.v4.app.ActivityCompat.requestPermissions(ActivityCompat.java:316)
            at com.journeyapps.barcodescanner.CaptureManager.openCameraWithPermission(CaptureManager.java:238)
            at com.journeyapps.barcodescanner.CaptureManager.onResume(CaptureManager.java:221)

**Comment by ymenager** [comment]
Also by the way, the code in CaptureManager is:

    public void onResume() {
        if(Build.VERSION.SDK_INT >= 23) {
            openCameraWithPermission();
        } else {
            barcodeView.resume();
        }
        openCameraWithPermission();
        beepManager.updatePrefs();
        inactivityTimer.start();
    }

That second openCameraWithPermission() outside the API 23 check probably shouldn't be in there ?

**Comment by ymenager** [comment]
By the way, easy future-proof fix: could you please allow CAMERA_PERMISSION_REQUEST to be non-final and changeable

**Comment by ymenager** [comment]
Actually it's most definitely not 65535.... it must pass this check:

f ((requestCode & 0xffffff00) != 0)

So 0 to 255 only
