### ISSUE TITLE
Preview Scrambled on Google Glass

### ISSUE THREAD

**Issue by noahdietz** [journeyapps/zxing-android-embedded#12]
Hi, thank you for making this project, it is extremely helpful.

When I use your method for adding the aar dependency with Gradle, it compiles and starts up fine, except that with Google Glass, the camera preview is all scrambled and fragmented (see screenshot). I found a SO answer (http://stackoverflow.com/a/22510862/3957976) that mentions there was a fix for this in the camera manager of the source. Is there any way to have this fix included or is that out of the scope of the minimalist idea? Thanks for your time and sorry if this has already been implemented and I'm wasting your time, still learning here.
![screenshot_2014-08-20-12-32-58 1](https://cloud.githubusercontent.com/assets/6644735/3979516/a849b8a6-2855-11e4-9bf6-2829052d6af1.png)

**Comment by rkistner** [comment]
Will you please test if this is still the case in the [3.x](https://github.com/journeyapps/zxing-android-embedded/tree/3.x) branch? A lot of the camera management code has been rewritten there.

**Comment by AugustoEst** [comment]
This problem still persists in the 3.x branch. With a new Google Glass coming out soon (for Enterprise), it would be great if there's a module for Glass that solves this issue.

**Comment by AugustoEst** [comment]
I have a problem importing the corrected *zxing-android-embedded.aar* into my Glass project. When I try to run:

`new IntentIntegrator(this).initiateScan();`

I get the following error:

```
java.lang.NoClassDefFoundError: com.google.zxing.BarcodeFormat
            at com.google.zxing.client.android.DecodeFormatManager.<clinit>(DecodeFormatManager.java:39)
            at com.journeyapps.barcodescanner.CompoundBarcodeView.initializeFromIntent(CompoundBarcodeView.java:128)
            at com.journeyapps.barcodescanner.CaptureManager.initializeFromIntent(CaptureManager.java:156)
            at com.journeyapps.barcodescanner.CaptureActivity.onCreate(CaptureActivity.java:24)
            at android.app.Activity.performCreate(Activity.java:5235)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1089)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2188)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2273)
            at android.app.ActivityThread.access$800(ActivityThread.java:138)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1236)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:149)
            at android.app.ActivityThread.main(ActivityThread.java:5045)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
            at dalvik.system.NativeStart.main(Native Method)
```

Any idea why? I used this guide to import the *.aar* file: http://stackoverflow.com/questions/29826717/how-to-import-a-aar-file-into-android-studio-1-1-0-and-use-it-in-my-code

**Comment by rkistner** [comment]
Yes, you will need to include zxing:core as well. It's just a jar file, so should be easy. Best is to just specify it as a dependency.

**Comment by AugustoEst** [comment]
Yep, works!

**Comment by rbarman** [comment]
@AugustoEst @rkistner Are you able to solve the issue of scrambled preview? 

I am a bit confused of how to set up my project. I currently have

    compile 'com.journeyapps:zxing-android-embedded:3.0.2@aar'
    compile 'com.google.zxing:core:3.2.0'
in my build.gradle. If we have to make adjustments in CameraManager.setDesiredParameters(), does this mean that I need to have axing-android-embedded src code in my project?

**Comment by AugustoEst** [comment]
@rbarman I applied the fixed mentioned above, generated a new .aar file and imported that one into my project. Like this:

```
compile project(':zxing-android-embedded-glass-fixed')
compile 'com.google.zxing:core:3.2.0'
```

**Comment by rkistner** [comment]
Sorry for taking so long to get to this. I added the mentioned workaround in version 3.0.3 - please test.

**Comment by soenkegissel** [comment]
I need to bring up this issue again as ticket #113. It's on a HTC One M8 with Cyanogenmod Nightlies with Android 6.0.1.
![2016_01_03_09 08 33](https://cloud.githubusercontent.com/assets/13346316/12078892/cf308dd8-b223-11e5-89d4-0c594dedbd56.png)

**Comment by soenkegissel** [comment]
I just had a friend over with a Nexus 5 phone for testing. As we could see this problem is caused by my early Android 6.0 version from Cyanogenmod. His official 6.0 is running smooth and the FPS camera problem did not come up. The on demand permission management worked fine also.

**Comment by rkistner** [comment]
Ok, thanks for the feedback.

It's possible that it's just a specific preview size that's not working.

There is an experimental branch for limiting the preview size, which may help as a workaround for a case like this:

https://github.com/journeyapps/zxing-android-embedded/tree/limit-preview-size

That branch is a little outdated though, will have to merge master into it.

**Comment by rkistner** [comment]
[v3.2.0](https://github.com/journeyapps/zxing-android-embedded/releases/tag/v3.2.0) contains some fixes which may solve this issue.

Please re-open if this issue still occurs.
