### ISSUE TITLE
Classnotfound when proguard is enabled

### ISSUE THREAD

**Issue by MufriA** [journeyapps/zxing-android-embedded#14]
In my sample app its works fine, however in my actual app where I have enabled proguard this is crashing, I cannot try without proguard due to infamous 65k dex issue (http://jakewharton.com/play-services-is-a-monolith/)

Any help is appreciated.

I have tried below lines in progurad
```
-keep class com.google.zxing.** {*;}
-keep class com.google.zxing.client.android.camera.open.**
-keep class com.google.zxing.client.android.common.executor.**
```

I use this in gradle

```
    compile 'com.embarkmobile:zxing-android-minimal:2.0.0@aar'
```

```
                        E  Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.zxing.client.android.CaptureActivity" on path: DexPathList[[zip file "/data/app/com.mufri.authe
                           nticatorplus.debug-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.mufri.authenticatorplus.debug-1, /vendor/lib, /system/lib]]
                        E      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                        E      at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                        E      at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                        E      at android.app.Instrumentation.newActivity(Instrumentation.java:1061)
                        E      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2101)
                        E      ... 11 more
```

Complete log is here - https://gist.github.com/MufriA/6d1dbe7ec11f0c6809f1

**Comment by rkistner** [comment]
Closing due to inactivity. Please re-open if it still occurs with the latest release and build tools.
