### ISSUE TITLE
Crash occurring due to camera instance being null on using custom capture activity.

### ISSUE THREAD

**Issue by masterlittle** [journeyapps/zxing-android-embedded#173]
FATAL EXCEPTION: main
                                                                       Process: com.grofers.inventory, PID: 30071
                                                                       java.lang.NullPointerException: Attempt to invoke virtual method 'void com.journeyapps.barcodescanner.camera.CameraInstance.setSurfaceHolder(android.view.SurfaceHolder)' on a null object reference
                                                                           at com.journeyapps.barcodescanner.CameraPreview.startCameraPreview(CameraPreview.java:472)
                                                                           at com.journeyapps.barcodescanner.CameraPreview.startPreviewIfReady(CameraPreview.java:320)
                                                                           at com.journeyapps.barcodescanner.CameraPreview.access$200(CameraPreview.java:48)
                                                                           at com.journeyapps.barcodescanner.CameraPreview$1.surfaceChanged(CameraPreview.java:130)
                                                                           at android.view.SurfaceView.updateWindow(SurfaceView.java:594)
                                                                           at android.view.SurfaceView.setFrame(SurfaceView.java:301)
                                                                           at android.view.View.layout(View.java:16648)
                                                                           at com.journeyapps.barcodescanner.CameraPreview.onLayout(CameraPreview.java:337)
                                                                           at android.view.View.layout(View.java:16651)
                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                                           at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                           at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                           at android.view.View.layout(View.java:16651)
                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                                           at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                           at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                           at android.view.View.layout(View.java:16651)
                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                                           at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1743)
                                                                           at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1586)
                                                                           at android.widget.LinearLayout.onLayout(LinearLayout.java:1495)
                                                                           at android.view.View.layout(View.java:16651)
                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                                           at android.widget.FrameLayout.layoutChildren(FrameLayout.java:336)
                                                                           at android.widget.FrameLayout.onLayout(FrameLayout.java:273)
                                                                           at com.android.internal.policy.PhoneWindow$DecorView.onLayout(PhoneWindow.java:2678)
                                                                           at android.view.View.layout(View.java:16651)
                                                                           at android.view.ViewGroup.layout(ViewGroup.java:5440)
                                                                           at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2183)
                                                                           at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1943)
                                                                           at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1119)
                                                                           at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6060)
                                                                           at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                           at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                           at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                           at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                           at android.os.Handler.handleCallback(Handler.java:746)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:148)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5443)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)

This crash is occurring when I extend CaptureActivity and set the orientation mode to portrait. The crash is sporadic but occurs numerous times which is impacting my app.

Here is my Capture Activity.

@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

```
    setContentView(com.google.zxing.client.android.R.layout.zxing_capture);
    barcodeScannerView = (CompoundBarcodeView)findViewById(com.google.zxing.client.android.R.id.zxing_barcode_scanner);

    capture = new CaptureManager(this, barcodeScannerView);
    capture.initializeFromIntent(getIntent(), savedInstanceState);
    capture.decode();
}
```

**Comment by rkistner** [comment]
I'll have to investigate this properly to see what the cause could be.

**Comment by rkistner** [comment]
Some related bugs have been fixed since this issue has been opened. Please open a new issue if this persists.
