### ISSUE TITLE
preview crash.

### ISSUE THREAD

**Issue by cat9** [journeyapps/zxing-android-embedded#192]
here are some bug report from my app.

Device:HTC_E9x  Android5.0.2

library:
 com.journeyapps:zxing-android-embedded:3.3.0@aar
 com.google.zxing:core:3.2.1

Fatal Exception: java.lang.RuntimeException: getParameters failed (empty parameters)
       at android.hardware.Camera.native_getParameters(Camera.java)
       at android.hardware.Camera.getParameters(Camera.java:3280)
       at com.journeyapps.barcodescanner.camera.CameraManager$CameraPreviewCallback.onPreviewFrame(CameraManager.java:103)
       at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1376)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:209)
       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by boshraViva** [comment]
you have to call
`@Override
	public void onResume() {
		barcodeView.resume();
		super.onResume();
	}

	@Override
	public void onPause() {
		barcodeView.pause();
		super.onPause();
	}`

and you have to make sure that these line will get called its may have some problems in nested fragment

**Comment by rkistner** [comment]
Bugs around this has been fixed, and will be in the 3.5.0 release. Please create a new issue if it still persists.
