### ISSUE TITLE
Met a crash when I change the camera to FRONT camera

### ISSUE THREAD

**Issue by FoxIvan** [journeyapps/zxing-android-embedded#196]
Met a crash when I change the camera to FRONT camera, have no idea about this

``` java
FATAL EXCEPTION: DecoderThread
  Process: com.xxx.xxx, PID: 32629
  java.lang.IllegalArgumentException: Crop rectangle does not fit within image data.
  at com.google.zxing.PlanarYUVLuminanceSource.<init>(PlanarYUVLuminanceSource.java:50)
  at com.journeyapps.barcodescanner.SourceData.createSource(SourceData.java:102)
  at com.journeyapps.barcodescanner.DecoderThread.createSource(DecoderThread.java:126)
  at com.journeyapps.barcodescanner.DecoderThread.decode(DecoderThread.java:134)
  at com.journeyapps.barcodescanner.DecoderThread.access$000(DecoderThread.java:22)
  at com.journeyapps.barcodescanner.DecoderThread$1.handleMessage(DecoderThread.java:38)
  at android.os.Handler.dispatchMessage(Handler.java:98)
  at android.os.Looper.loop(Looper.java:146)
  at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by rkistner** [comment]
Do you get this issue in the sample app? Which device?

**Comment by FoxIvan** [comment]
Samsung Tablet T-360, a very weird device. And it will not always reproduce. Guess the device has some issue. My code is pretty much the same as the sample. I've disabled the FRONT camera to capture an QR code, which was not a normal requirement.

**Comment by rkistner** [comment]
Some bugs around this has been fixed. Please open a new issue if it persists with version 3.5.0.
