### ISSUE TITLE
Android 7

### ISSUE THREAD

**Issue by lkwjohn** [journeyapps/zxing-android-embedded#214]
Does Zxing support Android 7? My previous application using Zxing 3.2.1 can't work on Android 7 phone.

**Comment by rkistner** [comment]
I don't have an Android 7 phone available, so haven't tested this yet. Does it also fail in an emulator?

**Comment by rafaelpivetta** [comment]
Your app crash in the moment to scan barcode or before?
In emulator I have tested and enable scan emulator, AVD (Android 7) with Camera Emulated. It's enough?

**Comment by addrum** [comment]
Works fine for me on 7.0. Do you have a stacktrace?

**Comment by lkwjohn** [comment]
W/com.google.zxing.client.android.camera.open.OpenCameraInterface: No cameras!
E/CameraInstance: Failed to open camera
java.lang.RuntimeException: Failed to open camera
   at com.journeyapps.barcodescanner.camera.CameraManager.open(CameraManager.java:125)
   at com.journeyapps.barcodescanner.camera.CameraInstance$3.run(CameraInstance.java:165)
   at android.os.Handler.handleCallback(Handler.java:751)
   at android.os.Handler.dispatchMessage(Handler.java:95)
   at android.os.Looper.loop(Looper.java:154)
   at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by rkistner** [comment]
@lkwjohn Which device (model) is giving the issue?

**Comment by commjoen** [comment]
works for me too

**Comment by rkistner** [comment]
Closing this for now, please open another issue if you have more details.
