### ISSUE TITLE
PreviewHandler’s surfaceCreated has been called twice, May cause failure of camera oepn

### ISSUE THREAD

**Issue by myth2loki** [journeyapps/zxing-android-embedded#23]
I installed demo apk, I found there is a issue that PreviewHandler's surfaceCreated has been called twice everytime I call initScan method. It's strange problem.
By the way, I got annother crash. I open settings panel from status bar of desktop while Scanning window is running. I got the error message below when I press back button to go back to scanning window:
W/CameraService(  284): CameraService::connect X (pid 32399) rejected (existing client).
W/CameraBase(32399): An error occurred while connecting to camera: 0
I/Camera2Mode(32399): fail
W/PreviewHandler(32399): Unexpected error initializing camera
W/PreviewHandler(32399): java.lang.RuntimeException: Fail to connect to camera service
W/PreviewHandler(32399): 	at android.hardware.Camera.open(Camera.java:421)
W/PreviewHandler(32399): 	at com.google.zxing.client.android.camera.open.OpenCameraInterface.open(OpenCameraInterface.java:64)
W/PreviewHandler(32399): 	at com.google.zxing.client.android.camera.open.OpenCameraInterface.open(OpenCameraInterface.java:85)
W/PreviewHandler(32399): 	at com.google.zxing.client.android.camera.CameraManager.openDriver(CameraManager.java:105)
W/PreviewHandler(32399): 	at com.google.zxing.client.android.PreviewHandler.initCamera(PreviewHandler.java:147)
W/PreviewHandler(32399): 	at com.google.zxing.client.android.PreviewHandler.surfaceCreated(PreviewHandler.java:49)
W/PreviewHandler(32399): 	at android.view.SurfaceView.updateWindow(SurfaceView.java:572)
W/PreviewHandler(32399): 	at android.view.SurfaceView.onWindowVisibilityChanged(SurfaceView.java:232)
W/PreviewHandler(32399): 	at android.view.View.dispatchWindowVisibilityChanged(View.java:8129)

**Comment by myth2loki** [comment]
OOOH. got a error message again.

02-13 15:34:05.711    1813-1813/example.zxing E/ActivityThread﹕ Performing stop of activity that is not resumed: {example.zxing/com.google.zxing.client.android.CaptureActivity}
    java.lang.RuntimeException: Performing stop of activity that is not resumed: {example.zxing/com.google.zxing.client.android.CaptureActivity}
            at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:3695)
            at android.app.ActivityThread.handleStopActivity(ActivityThread.java:3782)
            at android.app.ActivityThread.access$1100(ActivityThread.java:156)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1382)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:157)
            at android.app.ActivityThread.main(ActivityThread.java:5867)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:858)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:674)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by rkistner** [comment]
I'm unable to reproduce this. Which device are you testing on? Does the same happen on other devices?

**Comment by rkistner** [comment]
This logic has been rewritten in the 3.x branch. Open the issue again if you have a similar issue there.
