### ISSUE TITLE
onActivityResult  of activity is called instead of fragment

### ISSUE THREAD

**Issue by aaabidunique** [journeyapps/zxing-android-embedded#255]
#### Description of the problem:
IntentIntegrator.forSupportFragment(fragment) is calling onActivityResult of activity instead of fragment.
Help please.
FYI i am using latest 3.4.0 version and  exception is not the problem getting data in activity instead of fragment is the problem.

I checked on android 4.3 (Samsung galaxy note 2), android 5.0 (LeEco Le 1s & moto g 1st gen), android 7.1.1 (nexus 6p) all are giving the same problem.

Edit: This only happens if we have onActivityResult in activity also but if i remove it it works fine.

Logcat log
------------------
12-21 10:10:20.255 18351-18351/com.ali.deviceinfo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                    java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=114910, result=-1, data=Intent { act=com.google.zxing.client.android.SCAN flg=0x80000 (has extras) }} to activity {com.ali.deviceinfo/com.ali.deviceinfo.activity.HomeActivity}: java.lang.NullPointerException
                                                                        at android.app.ActivityThread.deliverResults(ActivityThread.java:3498)
                                                                        at android.app.ActivityThread.handleSendResult(ActivityThread.java:3541)
                                                                        at android.app.ActivityThread.access$1200(ActivityThread.java:159)
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                        at android.os.Looper.loop(Looper.java:137)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5414)
                                                                        at java.lang.reflect.Method.invokeNative(Native Method)
                                                                        at java.lang.reflect.Method.invoke(Method.java:525)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1187)
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
                                                                        at dalvik.system.NativeStart.main(Native Method)
                                                                     Caused by: java.lang.NullPointerException
                                                                        at com.ali.deviceinfo.activity.HomeActivity.onActivityResult(HomeActivity.java:439)
                                                                        at android.app.Activity.dispatchActivityResult(Activity.java:5558)
                                                                        at android.app.ActivityThread.deliverResults(ActivityThread.java:3494)
                                                                        at android.app.ActivityThread.handleSendResult(ActivityThread.java:3541) 
                                                                        at android.app.ActivityThread.access$1200(ActivityThread.java:159) 
                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364) 
                                                                        at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                        at android.os.Looper.loop(Looper.java:137) 
                                                                        at android.app.ActivityThread.main(ActivityThread.java:5414) 
                                                                        at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                        at java.lang.reflect.Method.invoke(Method.java:525) 
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1187) 
                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003) 
                                                                        at dalvik.system.NativeStart.main(Native Method)

**Comment by rkistner** [comment]
This is how Android works by design. You need to call `super.onActivityResult(requestCode, resultCode, data)` in the `Activity#onActivityResult` method - this takes care of passing it on to the Fragment.
