### ISSUE TITLE
RuntimeException: getParameters failed (empty parameters)

### ISSUE THREAD

**Issue by PaulWoitaschek** [journeyapps/zxing-android-embedded#270]
In my crashlogs I see a few RuntimeException where getParameters crashed. It appears for various devices, so far all API 23 and 24.

```
Exception java.lang.RuntimeException: getParameters failed (empty parameters)
android.hardware.Camera.native_getParameters (Camera.java)
android.hardware.Camera.getParameters (Camera.java:1951)
com.journeyapps.barcodescanner.camera.CameraManager.isTorchOn (CameraManager.java:470)
com.journeyapps.barcodescanner.camera.CameraManager.setTorch (CameraManager.java:449)
com.journeyapps.barcodescanner.camera.CameraInstance$1.run (CameraInstance.java:139)
android.os.Handler.handleCallback (Handler.java:739)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:234)
android.os.HandlerThread.run (HandlerThread.java:61)
```

**Comment by therottman** [comment]
I'm getting a similar issue, randomly on some devices:

`Exception [REVISION: 85538] caught=java.lang.RuntimeException: getParameters failed (empty parameters)
at android.hardware.Camera.native_getParameters(Native Method)
at android.hardware.Camera.getParameters(Camera.java:3113)
at com.journeyapps.barcodescanner.camera.CameraManager$CameraPreviewCallback.onPreviewFrame(CameraManager.java:103)
at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1281)
at android.os.Handler.dispatchMessage(Handler.java:111)
at android.os.Looper.loop(Looper.java:207)
at android.os.HandlerThread.run(HandlerThread.java:61)`

**Comment by PaulWoitaschek** [comment]
I'd be happy to make a PR. But as my current pull request is open for about 3 month now I'm not sure if this project is abandoned?

**Comment by rkistner** [comment]
@PaulWoitaschek Did you manage to find the issue? Issues like this are often device-specific, which makes it very difficult to debug without the device.

The project is not abandoned, but I have been slow with maintenance over the last few months. Looking at your PR now.

**Comment by nikeru8** [comment]
device: Redmi Note 4
Version: 6.0
crash location: BarcodeScannerView.java line 155 in BarcodeScannerView.setFlash()

**Comment by rkistner** [comment]
These errors are difficult to debug. It could be due to state management issues (still using the camera after it has been closed), or due to to a bug in the Camera framework of the device.

The best I can do for now is handle these errors by logging them, instead of letting the application crash.

@PaulWoitaschek Added a workaround for your issue in e3aed41746c33a72471f8aab16e5186ee4a5502c. The stack trace seems related to the torch, so it should be OK to just ignore the error.

@therottman Added workaround for your issue in 2cf4b60f0f1fb6181d0a0e5f6eee94803173364f. In this case it's an error when receiving a preview frame. If this happens either as a once-off frame issue, or because we were already closing the camera, the workaround should solve the issue. If it happens repeatedly, there may be a deeper underlying issue we'll have to investigate.

@nikeru8 Your issue may be the same as @PaulWoitaschek. If not, I'll need a proper stack trace to investigate.

**Comment by rkistner** [comment]
Fixed released in v3.5.0.

**Comment by therottman** [comment]
Tks! :)

**Comment by neeluagrawal** [comment]
java.lang.RuntimeException: getParameters failed (empty parameters)
        at android.hardware.Camera.native_getParameters(Native Method)
        at android.hardware.Camera.getParameters(Camera.java:1980)
        at jp.co.cyberagent.android.gpuimage.GPUImageRenderer.onPreviewFrame(GPUImageRenderer.java:150)
        at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1129)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6123)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)


getting this issue on motoG4
is there any solution for this problem?

**Comment by rastoabh19** [comment]
I'm facing similar issue on Motorola Moto G5 running on Android Nougat 7.0
Sourcecode : https://github.com/jfversluis/ZXingSample.git
Btw, sample code is working perfectly fine on iOS.
