### ISSUE TITLE
OOM error in BitMatrix

### ISSUE THREAD

**Issue by KushtrimPacaj** [journeyapps/zxing-android-embedded#306]
#### Description of the problem:
I'm seeing this error in Crashalytics, and it has crashed ~100 times.

```
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 117516 byte allocation with 81692 free bytes and 79KB until OOM
       at com.google.zxing.common.BitMatrix.<init>(BitMatrix.java:55)
       at com.google.zxing.common.HybridBinarizer.getBlackMatrix(HybridBinarizer.java:81)
       at com.google.zxing.BinaryBitmap.getBlackMatrix(BinaryBitmap.java:85)
       at com.google.zxing.qrcode.QRCodeReader.decode(QRCodeReader.java:77)
       at com.google.zxing.MultiFormatReader.decodeInternal(MultiFormatReader.java:171)
       at com.google.zxing.MultiFormatReader.decodeWithState(MultiFormatReader.java:85)
       at com.journeyapps.barcodescanner.Decoder.decode(Decoder.java:75)
       at com.journeyapps.barcodescanner.Decoder.decode(Decoder.java:49)
       at com.journeyapps.barcodescanner.DecoderThread.decode(DecoderThread.java:148)
       at com.journeyapps.barcodescanner.DecoderThread.access$000(DecoderThread.java:22)
       at com.journeyapps.barcodescanner.DecoderThread$1.handleMessage(DecoderThread.java:38)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:135)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

I'm using BarcodeView to have the preview inside my activity. I have modified the library very little, to fit my use case. I don't think these make any difference in regards to this problem, but I've included them here for brevity -> patch file:
[a.patch.txt](https://github.com/journeyapps/zxing-android-embedded/files/1094479/a.patch.txt)

**Which library version are you using?** 
3.5.0.

**Which phone/tablet are you using, and which Android version does it run?
Android 5.1.1

**Does the same happen on other devices or an emulator?**
I don't know exactly how to reproduce it, I just see the crash errors.

**Comment by rkistner** [comment]
OutOfMemoryErrors are difficult to debug. It could be because of a leak somewhere in the decoding algorithm (https://github.com/zxing/zxing project), this library, or the application itself - where the error happens in not always the main cause of the leak. Some memory profiling in your application while scanning might help to isolate the issue. If it seems to be related to the decoding, you can report the issue here: https://github.com/zxing/zxing/issues

**Comment by huaminghui** [comment]
I have also met this problem，In the  android 6.0 system

**Comment by KushtrimPacaj** [comment]
In this case the issue turned out to be the application, there was a memory somewhere else.
