### ISSUE TITLE
barcodescanner is nullpointerException

### ISSUE THREAD

**Issue by huaminghui** [journeyapps/zxing-android-embedded#312]
java.lang.NullPointerException: Attempt to get length of null array
	at com.journeyapps.barcodescanner.l.<init>(SourceData.java:50)
	at com.journeyapps.barcodescanner.a.c$a.onPreviewFrame(CameraManager.java:101)
	at android.hardware.Camera$EventHandler.handleMessage(Camera.java:1279)
	at android.os.Handler.dispatchMessage(Handler.java:111)
	at android.os.Looper.loop(Looper.java:194)
	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by CatalinPrata** [comment]
This should be fixed in 3.5.0, @huaminghui what version are you using? Please see https://github.com/journeyapps/zxing-android-embedded/issues/268

**Comment by rkistner** [comment]
Closing old issues - please open a new issue if you still run into this with the latest version.
