### ISSUE TITLE
app crashing with  java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by yashasvigirdhar** [journeyapps/zxing-android-embedded#332]
#### Description of the problem:
App crashing on some devices

**Which library version are you using?** 
3.3.0.

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**
HTC, Micromax, Lenovo, Huawei

**Does the same happen on other devices or an emulator?** No

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**

Can't reproduce as it's not consistent. I am using `decodeContinuous` function. 

**In the case of an error do you have a stack trace or adb logs?**
stack trace of crash : 

```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=460800; index=479200
       at com.journeyapps.barcodescanner.SourceData.rotateCW(SourceFile:185)
       at com.journeyapps.barcodescanner.SourceData.rotateCameraPreview(SourceFile:158)
       at com.journeyapps.barcodescanner.SourceData.createSource(SourceFile:97)
       at com.journeyapps.barcodescanner.DecoderThread.createSource(SourceFile:126)
       at com.journeyapps.barcodescanner.DecoderThread.decode(SourceFile:134)
       at com.journeyapps.barcodescanner.DecoderThread.access$000(SourceFile:22)
       at com.journeyapps.barcodescanner.DecoderThread$1.handleMessage(SourceFile:38)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by rkistner** [comment]
Closing old issues - please open a new issue if you still run into this with the latest version.
