### ISSUE TITLE
Opening Camera Issue with Nougat Android Version 

### ISSUE THREAD

**Issue by kshkrao3** [journeyapps/zxing-android-embedded#347]
#### DecoratedBarcodeView does not display camera for ContinuousCaptureActivity in Android Nougat:

**Library** - 3.5.0

**Phone** - Micromax Canvas Infinity - Android 7.1.2 API 25

**Device or Emulator** - Device

**Reproducible** - Yes, It is as simple as ContinuousCaptureActivity provided in the GIT

**StackTrace** - Failed to open camera
                                                                           java.lang.RuntimeException: Fail to connect to camera service
                                                                               at android.hardware.Camera.<init>(Camera.java:588)
                                                                               at android.hardware.Camera.open(Camera.java:411)
                                                                               at com.google.zxing.client.android.camera.open.OpenCameraInterface.open(OpenCameraInterface.java:83)
                                                                               at com.journeyapps.barcodescanner.camera.CameraManager.open(CameraManager.java:138)
                                                                               at com.journeyapps.barcodescanner.camera.CameraInstance$3.run(CameraInstance.java:190)
                                                                               at android.os.Handler.handleCallback(Handler.java:751)
                                                                               at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                               at android.os.Looper.TinnoLoop(Looper.java:138)
                                                                               at android.os.Looper.loop(Looper.java:208)
                                                                               at android.os.HandlerThread.run(HandlerThread.java:61)

I was expecting that it would ask for permission automatically. Should the permissions code be implemented at the application level?

**Comment by bernatpl** [comment]
Same in Android 6.0.1 API 23

See log:
```
D/CameraPreview: resume()
D/CameraInstance: Opening camera
W/CameraBase: An error occurred while connecting to camera: 0
E/CameraInstance: Failed to open camera
  java.lang.RuntimeException: Fail to connect to camera service
    at android.hardware.Camera.<init>(Camera.java:518)
    at android.hardware.Camera.open(Camera.java:360)
    at com.google.zxing.client.android.camera.open.OpenCameraInterface.open(OpenCameraInterface.java:83)
    at com.journeyapps.barcodescanner.camera.CameraManager.open(CameraManager.java:138)
    at com.journeyapps.barcodescanner.camera.CameraInstance$3.run(CameraInstance.java:190)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.os.HandlerThread.run(HandlerThread.java:61)
D/CameraInstance: Configuring camera
E/CameraInstance: Failed to configure camera
  java.lang.RuntimeException: Camera not open
    at com.journeyapps.barcodescanner.camera.CameraManager.configure(CameraManager.java:157)
    at com.journeyapps.barcodescanner.camera.CameraInstance$4.run(CameraInstance.java:203)
    at android.os.Handler.handleCallback(Handler.java:739)
    at android.os.Handler.dispatchMessage(Handler.java:95)
    at android.os.Looper.loop(Looper.java:148)
    at android.os.HandlerThread.run(HandlerThread.java:61)
D/CameraPreview: pause()
D/CameraInstance: Closing camera
```

**Comment by bernatpl** [comment]
It happened to me because the camera permission was not granted for the application.

**Comment by usamashahid049** [comment]
@kshkrao3 This issue also happened to me. If you find any solution kindly share with me. 
Thanks in advance.

**Comment by rkistner** [comment]
The permission request is part of CaptureActivity, not the BarcodeView. So if you create a custom Activity, you need to do the permissions as part of that.
