### ISSUE TITLE
Fail to connect to camera service

### ISSUE THREAD

**Issue by ckenergy** [journeyapps/zxing-android-embedded#358]
#### Description of the problem:
in ScannerActivity start a NewActivity, in NewActivity onResume use  `camera = Camera.open();` got Fail to connect to camera service error; 
i think in `CameraInstance.close()` method use `cameraThread.enqueue(closer)` is delay `NewActivity.onResume()` , so i call `Camera.open()` the camera is not release;
when i use closer.run() instead cameraThread.enqueue(closer), it work

**Which library version are you using?** E.g. 3.2.0.
3.5.0
**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**
android 4.4

**Comment by leohan1992** [comment]
I got the same error
```
01-01 00:30:37.378 5908-5943/com.sunvua.android.createtagutil E/CameraInstance: Failed to open camera
                                                                                java.lang.RuntimeException: Fail to connect to camera service
                                                                                    at android.hardware.Camera.<init>(Camera.java:654)
                                                                                    at android.hardware.Camera.open(Camera.java:495)
                                                                                    at com.google.zxing.client.android.camera.open.OpenCameraInterface.open(OpenCameraInterface.java:83)
                                                                                    at com.journeyapps.barcodescanner.camera.CameraManager.open(CameraManager.java:138)
                                                                                    at com.journeyapps.barcodescanner.camera.CameraInstance$3.run(CameraInstance.java:190)
                                                                                    at android.os.Handler.handleCallback(Handler.java:815)
                                                                                    at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                                    at android.os.Looper.loop(Looper.java:194)
                                                                                    at android.os.HandlerThread.run(HandlerThread.java:61)
```
library version 3.5.0  
android 5.0 on an company pda

**Comment by adammcelhaney** [comment]
Same error here:



E/Camera: Error 2
D/CameraInstance: Starting preview
E/CameraInstance: Failed to start preview
		  java.io.IOException: setPreviewTexture failed
			  at android.hardware.Camera.setPreviewSurface(Native Method)
			  at android.hardware.Camera.setPreviewDisplay(Camera.java:652)
			  at com.journeyapps.barcodescanner.camera.CameraSurface.setPreview(CameraSurface.java:43)
			  at com.journeyapps.barcodescanner.camera.CameraManager.setPreviewDisplay(CameraManager.java:170)
			  at com.journeyapps.barcodescanner.camera.CameraInstance$5.run(CameraInstance.java:219)
			  at android.os.Handler.handleCallback(Handler.java:751)
			  at android.os.Handler.dispatchMessage(Handler.java:95)
			  at android.os.Looper.loop(Looper.java:154)
			  at android.os.HandlerThread.run(HandlerThread.java:61)


Library v 3.5
Samsung Galaxy Amp Prime: Android v 7.1.1

**Comment by rkistner** [comment]
For the original issue: By design, the camera management is performed in a background thread, so the camera may still be in use by the time the Activity is closed.

I recommend retrying opening the camera for a second if two.

For the other comments, please open a new issue if you still have trouble with the latest version.
