### ISSUE TITLE
Error inflating class com.journeyapps.barcodescanner.DecoratedBarcodeView

### ISSUE THREAD

**Issue by handinux** [journeyapps/zxing-android-embedded#369]
#### Description of the problem:
Hi. i get this error when run app
Binary XML file line #13: Error inflating class com.journeyapps.barcodescanner.DecoratedBarcodeView

my XML : 

<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:paddingBottom="@dimen/activity_vertical_margin"
    android:orientation="vertical"
    android:gravity="center_horizontal"
    tools:context=".view.impl.activities.qrpayment.QRActivity"
    tools:layout_editor_absoluteY="25dp">

    <com.journeyapps.barcodescanner.DecoratedBarcodeView
        android:id="@+id/zxing_barcode_surface"
        android:layout_width="match_parent"
        android:layout_height="match_parent" />

    <capital.kian.kiandigital.zpackages.widgets.PersianTextView
        android:id="@+id/persianTextView"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginTop="10dp"
        android:text="@string/enter_code_by_hand" />

    <capital.kian.kiandigital.zpackages.widgets.PersianEditText
        android:id="@+id/editText"
        android:layout_width="194dp"
        android:layout_height="wrap_content"
        android:layout_marginEnd="8dp"
        android:layout_marginStart="8dp"
        android:layout_marginTop="16dp"
        android:ems="10"
        android:inputType="number"
        android:maxLength="6"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintHorizontal_bias="0.497"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/persianTextView" />

    <capital.kian.kiandigital.zpackages.widgets.PersianButton
        android:id="@+id/button2"
        android:layout_width="192dp"
        android:layout_height="wrap_content"
        android:layout_marginBottom="8dp"
        android:layout_marginEnd="8dp"
        android:layout_marginStart="8dp"
        android:layout_marginTop="24dp"
        android:text="@string/submit"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintHorizontal_bias="0.497"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/editText"
        app:layout_constraintVertical_bias="0.0" />

</LinearLayout>

Code : 

public final class QRActivity extends BaseActivity<QrPresenter, QrView> implements QrView {

    private DecoratedBarcodeView barcodeView;
    private BeepManager beepManager;

    @Inject
    PresenterFactory<QrPresenter> mPresenterFactory;

    private BarcodeCallback callback = new BarcodeCallback() {
        @Override
        public void barcodeResult(BarcodeResult result) {

        }

        @Override
        public void possibleResultPoints(List<ResultPoint> resultPoints) {
        }
    };

    // Your presenter is available using the mPresenter variable

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_qr);
        barcodeView = (DecoratedBarcodeView) findViewById(R.id.zxing_barcode_surface);
        barcodeView.decodeContinuous(callback);
        beepManager = new BeepManager(this);

        // Your code here
        // Do not call mPresenter from here, it will be null! Wait for onStart or onPostCreate.
    }

    @Override
    protected void setupComponent(@NonNull AppComponent parentComponent) {
        DaggerQrViewComponent.builder()
                .appComponent(parentComponent)
                .qrViewModule(new QrViewModule())
                .build()
                .inject(this);
    }

    @NonNull
    @Override
    protected PresenterFactory<QrPresenter> getPresenterFactory() {
        return mPresenterFactory;
    }

    @Override
    public void onVisibilityChanged(boolean isOpen) {

    }

    @Override
    protected void onResume() {
        super.onResume();
        barcodeView.resume();
    }

    @Override
    protected void onPause() {
        super.onPause();
        barcodeView.pause();
    }

}

**Which library version are you using?** E.g. 3.2.0.
3.5.0
**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**
Android 7 Honor 8 lite
**Does the same happen on other devices or an emulator?**
Yes
**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**

**In the case of an error do you have a stack trace or adb logs?**

**Comment by rkistner** [comment]
Does the stack trace contain any additional details?

**Comment by ralphgabrielle** [comment]
This also occurs on Android Oreo, any fix ?

**Comment by rkistner** [comment]
This is not enough info to debug. We need the following additional info:
1. The full stack trace.
2. Which devices / Android versions it happens on (all of them, or only specific versions?).
3. Whether it is also reproducable with the sample application.

**Comment by dhruv036** [comment]
java.lang.RuntimeException: Unable to start activity ComponentInfo{io.stempedia.pictoblox/io.stempedia.pictoblox.CustomScanner}: android.view.InflateException: Binary XML file line #16 in io.stempedia.pictoblox:layout/activity_custom_scanner: Binary XML file line #16 in io.stempedia.pictoblox:layout/activity_custom_scanner: Error inflating class com.journeyapps.barcodescanner.DecoratedBarcodeView
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3616)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3780)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2251)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:233)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8068)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
                                                                                                    Caused by: android.view.InflateException: Binary XML file line #16 in io.stempedia.pictoblox:layout/activity_custom_scanner: Binary XML file line #16 in io.stempedia.pictoblox:layout/activity_custom_scanner: Error inflating class com.journeyapps.barcodescanner.DecoratedBarcodeView
                                                                                                    Caused by: android.view.InflateException: Binary XML file line #16 in io.stempedia.pictoblox:layout/activity_custom_scanner: Error inflating class com.journeyapps.barcodescanner.DecoratedBarcodeView
                                                                                                    Caused by: java.lang.reflect.InvocationTargetException
                                                                                                    	at java.lang.reflect.Constructor.newInstance0(Native Method)
                                                                                                    	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
                                                                                                    	at android.view.LayoutInflater.createView(LayoutInflater.java:876)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:1028)
                                                                                                    	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:983)
                                                                                                    	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1156)
                                                                                                    	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1117)
                                                                                                    	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1159)
                                                                                                    	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1117)
                                                                                                    	at android.view.LayoutInflater.rInflate(LayoutInflater.java:1159)
                                                                                                    	at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:1117)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:704)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:556)
                                                                                                    	at android.view.LayoutInflater.inflate(LayoutInflater.java:503)
                                                                                                    	at androidx.appcompat.app.AppCompatDelegateImpl.setContentView(AppCompatDelegateImpl.java:699)
                                                                                                    	at androidx.appcompat.app.AppCompatActivity.setContentView(AppCompatActivity.java:195)
                                                                                                    	at io.stempedia.pictoblox.CustomScanner.onCreate(CustomScanner.kt:66)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:8006)
                                                                                                    	at android.app.Activity.performCreate(Activity.java:7990)
                                                                                                    	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1329)
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3589)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3780)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2251)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:233)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8068)
2023-06-07 14:03:24.105 17465-17465 AndroidRuntime          io.stempedia.pictoblox               E  	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:631)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:978)
                                                                                                    Caused by: java.lang.IllegalArgumentException: There is no a com.journeyapps.barcodescanner.BarcodeView on provided layout with the id "zxing_barcode_surface".
                                                                                                    	at com.journeyapps.barcodescanner.DecoratedBarcodeView.initialize(DecoratedBarcodeView.java:96)
                                                                                                    	at com.journeyapps.barcodescanner.DecoratedBarcodeView.<init>(DecoratedBarcodeView.java:69)
                                                                                                    	... 32 more
