### ISSUE TITLE
IllegalArgumentException on closing camera without scanning barcode

### ISSUE THREAD

**Issue by manojs001** [journeyapps/zxing-android-embedded#375]
#### Description of the problem:
I am developing my app using kotlin, the crash occurs on pressing back button without scanning anything. Simply call initiateScan() then close your CaptureActivity

**Which library version are you using?** E.g. 3.2.0.
3.5.0

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**
Device android 7.1.2 (Oneplus X)

**Does the same happen on other devices or an emulator?**
Yes

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**
My Sample Code:
1. In Activity 
qrButton.setOnClickListener {
            val intentIntegrator = IntentIntegrator(this)
            intentIntegrator.setOrientationLocked(false)
            intentIntegrator.initiateScan()
        }
onAcitivityResult is not called as exception occurs before that

**In the case of an error do you have a stack trace or adb logs?**

E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.xxxxx, PID: 15985
                  java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=49374, result=0, data=null} to activity {com.xxxxx/com.xxxxx.XActivity}: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter data
                      at android.app.ActivityThread.deliverResults(ActivityThread.java:4126)
                      at android.app.ActivityThread.handleSendResult(ActivityThread.java:4169)
                      at android.app.ActivityThread.-wrap20(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1552)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6186)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
                   Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter data
                      at com.xxxxx.XActivity.onActivityResult(ProductKeyActivity.kt)
                      at android.app.Activity.dispatchActivityResult(Activity.java:6937)
                      at android.app.ActivityThread.deliverResults(ActivityThread.java:4122)
                      at android.app.ActivityThread.handleSendResult(ActivityThread.java:4169) 
                      at android.app.ActivityThread.-wrap20(ActivityThread.java) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1552) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:154) 
                      at android.app.ActivityThread.main(ActivityThread.java:6186) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)

**Comment by rkistner** [comment]
> Caused by: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter data
at com.xxxxx.XActivity.onActivityResult(ProductKeyActivity.kt)
at android.app.Activity.dispatchActivityResult(Activity.java:6937)

This looks like a Kotlin-specific issue, with the data parameter marked as "NotNull".

Try marking the data parameter as nullable - something like this in Kotlin::

```
onActivityResult(requestCode: Int, resultCode: Int, data: Intent?)
```

**Comment by manojs001** [comment]
It worked, silly me. Thank you

**Comment by craigRSA** [comment]
thanks! that worked for me too
