### ISSUE TITLE
 Failed to open camera

### ISSUE THREAD

**Issue by yangfuzhi** [journeyapps/zxing-android-embedded#380]
03-26 16:39:01.141 12168-12896/com.hema.daixi E/CameraInstance: Failed to open camera
                                                                java.lang.RuntimeException: Fail to connect to camera service
                                                                    at android.hardware.Camera.<init>(Camera.java:568)
                                                                    at android.hardware.Camera.open(Camera.java:408)
                                                                    at com.google.zxing.client.android.camera.open.OpenCameraInterface.open(OpenCameraInterface.java:83)
                                                                    at com.journeyapps.barcodescanner.camera.CameraManager.open(CameraManager.java:138)
                                                                    at com.journeyapps.barcodescanner.camera.CameraInstance$4.run(CameraInstance.java:218)
                                                                    at android.os.Handler.handleCallback(Handler.java:739)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                    at android.os.Looper.loop(Looper.java:145)
                                                                    at android.os.HandlerThread.run(HandlerThread.java:61)
03-26 16:39:01.141 12168-12896/com.hema.daixi E/CameraInstance: Failed to configure camera
                                                                java.lang.RuntimeException: Camera not open
                                                                    at com.journeyapps.barcodescanner.camera.CameraManager.configure(CameraManager.java:157)
                                                                    at com.journeyapps.barcodescanner.camera.CameraInstance$5.run(CameraInstance.java:231)
                                                                    at android.os.Handler.handleCallback(Handler.java:739)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                    at android.os.Looper.loop(Looper.java:145)
                                                                    at android.os.HandlerThread.run(HandlerThread.java:61)
>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
API:22 Android 5.1.1  Device:Samsung SM-J310 
Version:3.6.0

Help me ~~~I am  in  Hurry

**Comment by jackwilsdon** [comment]
Have you added the camera permission to your app's manifest?

**Comment by yangfuzhi** [comment]
@jackwilsdon Yeh!I added this

**Comment by tee-dee** [comment]
Also have this issue. Manifest (snippet):

    <uses-permission android:name="android.permission.CAMERA" />
    <uses-feature android:name="android.hardware.camera" />
    <uses-feature android:name="android.hardware.camera.autofocus" />

No issue before testing on a 6.0+ Android version
