### ISSUE TITLE
FATAL EXCEPTION: DecoderThread java.lang.NoClassDefFoundError: java.nio.charset.StandardCharsets (API level < 19)

### ISSUE THREAD

**Issue by kuleshovdv** [journeyapps/zxing-android-embedded#391]
#### Description of the problem:

When API level less 19 I get crash after scanning PDF-417 code.
```
FATAL EXCEPTION: DecoderThread
java.lang.NoClassDefFoundError: java.nio.charset.StandardCharsets
at com.google.zxing.pdf417.decoder.DecodedBitStreamParser.decode(DecodedBitStreamParser.java:96)
at com.google.zxing.pdf417.decoder.PDF417ScanningDecoder.decodeCodewords(PDF417ScanningDecoder.java:534)
at com.google.zxing.pdf417.decoder.PDF417ScanningDecoder.createDecoderResultFromAmbiguousValues(PDF417ScanningDecoder.java:309)
at com.google.zxing.pdf417.decoder.PDF417ScanningDecoder.createDecoderResult(PDF417ScanningDecoder.java:278)
at com.google.zxing.pdf417.decoder.PDF417ScanningDecoder.decode(PDF417ScanningDecoder.java:124)
at com.google.zxing.pdf417.PDF417Reader.decode(PDF417Reader.java:87)
at com.google.zxing.pdf417.PDF417Reader.decode(PDF417Reader.java:61)
at com.google.zxing.MultiFormatReader.decodeInternal(MultiFormatReader.java:171)
at com.google.zxing.MultiFormatReader.decodeWithState(MultiFormatReader.java:85)
at com.journeyapps.barcodescanner.Decoder.decode(Decoder.java:75)
at com.journeyapps.barcodescanner.Decoder.decode(Decoder.java:49)
at com.journeyapps.barcodescanner.DecoderThread.decode(DecoderThread.java:146)
at com.journeyapps.barcodescanner.DecoderThread.access$000(DecoderThread.java:22)
at com.journeyapps.barcodescanner.DecoderThread$1.handleMessage(DecoderThread.java:38)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:213)
at android.os.HandlerThread.run(HandlerThread.java:60)
```

**Which library version are you using?** 
3.6.0
(3.5.0 works perfectly)

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**
Different devices. Android 4.4

**Does the same happen on other devices or an emulator?**
Yes

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**
Yes

**In the case of an error do you have a stack trace or adb logs?**
Yes

**Comment by rkistner** [comment]
Which version of zxing:core are you using? See the readme for notes API compatibility.

**Comment by kuleshovdv** [comment]
```
    compile 'com.journeyapps:zxing-android-embedded:3.6.0'
    compile 'com.google.zxing:core:3.3.0'
```

**Comment by rkistner** [comment]
It's important to use the `{ transitive = false }` as mentioned in the readme:

```
compile('com.journeyapps:zxing-android-embedded:3.6.0') { transitive = false }
```

Without this, a later version of `zxing:core` is included automatically.
