### ISSUE TITLE
Error while launching scanner acivitiy which contains CompoundBarcodeView

### ISSUE THREAD

**Issue by SushantPatekar** [journeyapps/zxing-android-embedded#396]
#### Description of the problem:
We are using this following code to open QR code scanning screen 
IntentIntegrator _intent = new IntentIntegrator(this).addExtra(Intents.Scan.CHARACTER_SET, "ISO-8859-1");
                _intent.setCaptureActivity(ScannerActitivity.class);
                _intent.initiateScan();

& inside ScannerAcitivity 
      barcodeScannerView = (CompoundBarcodeView) findViewById(R.id.zxing_barcode_scanner);
        capture = new CaptureManager(this, barcodeScannerView);
        capture.initializeFromIntent(getIntent(), savedInstanceState);
        capture.decode();

we facing this error -(refer below image URL)
It won't allow accessing the camera of the device.
https://imgur.com/a/cPnZuud

Kindly help us with any solution.

**Which library version are you using?** E.g. com.journeyapps:zxing-android-embedded:3.4.0

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)** Specific to Android 5.0+ (It works on 6.0)

**Does the same happen on other devices or an emulator?** 

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**

**In the case of an error do you have a stack trace or adb logs?**
Failed to open camera
    java.lang.RuntimeException: Fail to connect to camera service
        at android.hardware.Camera.<init>(Camera.java:637)
        at android.hardware.Camera.open(Camera.java:371)
        at com.google.zxing.client.android.camera.open.OpenCameraInterface.open(OpenCameraInterface.java:83)
        at com.journeyapps.barcodescanner.camera.CameraManager.open(CameraManager.java:133)
        at com.journeyapps.barcodescanner.camera.CameraInstance$3.run(CameraInstance.java:181)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:135)
        at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by rkistner** [comment]
Does the same happen on those devices if you use the sample application? Or is it specific to your application? (Download the sample app here: https://github.com/journeyapps/zxing-android-embedded/releases)
