### ISSUE TITLE
Zxing Error -  llegalStateException at com.google.zxing.client.android.camera.CameraManager.setManualCameraId 

### ISSUE THREAD

**Issue by sushantgosavi22** [journeyapps/zxing-android-embedded#397]
I am getting Crash while scanning bar code on some device only most of time Redmi devices  
IllegalStateException at com.google.zxing.client.android.camera.CameraManager.setManualCameraId 

Please find my crash log 

Library version and build.gradle file 
/*Barcode Scanner */
    compile 'com.journeyapps:zxing-android-embedded:2.0.1@aar'
    compile 'com.journeyapps:zxing-android-legacy:2.0.1@aar'
    compile 'com.journeyapps:zxing-android-integration:2.0.1@aar'
    compile 'com.google.zxing:core:3.0.1'
/*Barcode Scanner */ 

** Please find below version and model 
ANDROID_VERSION=7.1.2
PHONE_MODEL=Redmi 4
**

Log 

ANDROID_VERSION=7.1.2
PHONE_MODEL=Redmi 4
CUSTOM_DATA=
STACK_TRACE=java.lang.RuntimeException: Unable to resume activity {com.rsystem.icas/com.google.zxing.client.android.CaptureActivity}: java.lang.IllegalStateException
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3485)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3525)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1566)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:163)
at android.app.ActivityThread.main(ActivityThread.java:6221)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)
**Caused by: java.lang.IllegalStateException
at com.google.zxing.client.android.camera.CameraManager.setManualCameraId(CameraManager.java:284)**
at com.google.zxing.client.android.CaptureActivity.onResume(CaptureActivity.java:225)
at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1270)
at android.app.Activity.performResume(Activity.java:6977)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3462)
... 8 more
java.lang.IllegalStateException
at com.google.zxing.client.android.camera.CameraManager.setManualCameraId(CameraManager.java:284)
at com.google.zxing.client.android.CaptureActivity.onResume(CaptureActivity.java:225)
at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1270)
at android.app.Activity.performResume(Activity.java:6977)
at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3462)
at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3525)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1566)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:163)
at android.app.ActivityThread.main(ActivityThread.java:6221)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794)

LOGCAT=05-21 19:14:16.791 D/CAMERA  (15371): Camera found
05-21 19:14:16.792 I/Timeline(15371): Timeline: Activity_launch_request time:224080879 intent:Intent { act=com.google.zxing.client.android.SCAN flg=0x4080000 cmp=com.rsystem.icas/com.google.zxing.client.android.CaptureActivity (has extras) }
05-21 19:14:16.815 D/CAMERA  (15371): Camera found
05-21 19:14:16.816 I/Timeline(15371): Timeline: Activity_launch_request time:224080903 intent:Intent { act=com.google.zxing.client.android.SCAN flg=0x4080000 cmp=com.rsystem.icas/com.google.zxing.client.android.CaptureActivity (has extras) }
05-21 19:14:16.832 D/CAMERA  (15371): Camera found
05-21 19:14:16.832 I/Timeline(15371): Timeline: Activity_launch_request time:224080919 intent:Intent { act=com.google.zxing.client.android.SCAN flg=0x4080000 cmp=com.rsystem.icas/com.google.zxing.client.android.CaptureActivity (has extras) }
05-21 19:14:16.847 D/CAMERA  (15371): Camera found
05-21 19:14:16.848 I/Timeline(15371): Timeline: Activity_launch_request time:224080935 intent:Intent { act=com.google.zxing.client.android.SCAN flg=0x4080000 cmp=com.rsystem.icas/com.google.zxing.client.android.CaptureActivity (has extras) }
05-21 19:14:16.864 D/CAMERA  (15371): Camera found
05-21 19:14:16.864 I/Timeline(15371): Timeline: Activity_launch_request time:224080951 intent:Intent { act=com.google.zxing.client.android.SCAN flg=0x4080000 cmp=com.rsystem.icas/com.google.zxing.client.android.CaptureActivity (has extras) }
05-21 19:14:16.878 I/Choreographer(15371): Skipped 277 frames!  The application may be doing too much work on its main thread.
05-21 19:14:18.911 I/art     (15371): Background sticky concurrent mark sweep GC freed 144479(8MB) AllocSpace objects, 1(20KB) LOS objects, 25% free, 26MB/34MB, paused 2.371ms total 116.931ms

**Comment by sushantgosavi22** [comment]
Facing this issue from last 2 months cant able to find any thing from internet and other sources, help appreciate

**Comment by rkistner** [comment]
You are on a very old version of the library. Try upgrading to the latest version - it's quite likely that the issue has been fixed by now.
