### ISSUE TITLE
Didn't find class "com.google.zxing.BarcodeFormat"

### ISSUE THREAD

**Issue by jaag12** [journeyapps/zxing-android-embedded#452]
When starting the detection, it throws me the following error: Did not find class "com.google.zxing.BarcodeFormat"

` java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/zxing/BarcodeFormat;
        at com.google.zxing.client.android.DecodeFormatManager.<clinit>(DecodeFormatManager.java:37)
        at com.journeyapps.barcodescanner.DecoratedBarcodeView.initializeFromIntent(DecoratedBarcodeView.java:133)
        at com.journeyapps.barcodescanner.CaptureManager.initializeFromIntent(CaptureManager.java:167)
        at com.journeyapps.barcodescanner.CaptureActivity.onCreate(CaptureActivity.java:24)
        at android.app.Activity.performCreate(Activity.java:6876)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)
        at android.app.ActivityThread.access$1100(ActivityThread.java:222)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:158)
        at android.app.ActivityThread.main(ActivityThread.java:7229)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.zxing.BarcodeFormat" on path: DexPathList[[zip file "/data/app/es.topdigital.locksmartkey-1/base.apk"],nativeLibraryDirectories=[/data/app/es.topdigital.locksmartkey-1/lib/arm64, /vendor/lib64, /system/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at com.google.zxing.client.android.DecodeFormatManager.<clinit>(DecodeFormatManager.java:37) 
        at com.journeyapps.barcodescanner.DecoratedBarcodeView.initializeFromIntent(DecoratedBarcodeView.java:133) 
        at com.journeyapps.barcodescanner.CaptureManager.initializeFromIntent(CaptureManager.java:167) 
        at com.journeyapps.barcodescanner.CaptureActivity.onCreate(CaptureActivity.java:24) 
        at android.app.Activity.performCreate(Activity.java:6876) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1135) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3207) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350) 
        at android.app.ActivityThread.access$1100(ActivityThread.java:222) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:158) 
        at android.app.ActivityThread.main(ActivityThread.java:7229) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120) 
    	Suppressed: java.lang.ClassNotFoundException: com.google.zxing.BarcodeFormat
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 17 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available`

The version I am using is 3.6.0 and implementation 'com.android.support:appcompat-v7:28.0.0'

**Comment by terminalesIndra** [comment]
Include implementation 'com.google.zxing:core:3.3.2' solve this error

**Comment by rkistner** [comment]
This is typically an issue with the dependency configuration.

If it's not solved by "Clean Project" and "Rebuild Project", post a sample project reproducing the issue.

**Comment by TravBradfield** [comment]
> implementation 'com.google.zxing:core:3.3.2'

@pcamlop 
Hey man, where did you include this implementation line? I've tried in the app gradle and I've tried in barcodescanner.gradle both make no difference. 

Thanks!
