### ISSUE TITLE
Autofocus failed on Android 9

### ISSUE THREAD

**Issue by ursvaibhav01** [journeyapps/zxing-android-embedded#457]
When integrated scanner library with Android 9 smartphone, following stack trace keeps appearing

W/AutoFocusManager: Unexpected exception while focusing
                    java.lang.RuntimeException: autoFocus failed
                        at android.hardware.Camera.native_autoFocus(Native Method)
                        at android.hardware.Camera.autoFocus(Camera.java:1366)
                        at com.journeyapps.barcodescanner.camera.AutoFocusManager.focus(AutoFocusManager.java:104)
                        at com.journeyapps.barcodescanner.camera.AutoFocusManager.access$100(AutoFocusManager.java:31)
                        at com.journeyapps.barcodescanner.camera.AutoFocusManager$1.handleMessage(AutoFocusManager.java:57)
                        at android.os.Handler.dispatchMessage(Handler.java:102)
                        at android.os.Looper.loop(Looper.java:193)
                        at android.os.HandlerThread.run(HandlerThread.java:65)

library version - 3.6.0

Happens on Samsung Android 9

Haven't tried on other Android 9 devices

**Comment by rkistner** [comment]
Merging into #459.

**Comment by massimilianochiodi** [comment]
Have same problem on android 12
