### ISSUE TITLE
get parameters failed on Android 9

### ISSUE THREAD

**Issue by ursvaibhav01** [journeyapps/zxing-android-embedded#459]
Following stack trace keeps appearing on Samsung Android 9 smartphone. I am using library version 3.6.0

E/CameraInstance: Failed to configure camera
                  java.lang.RuntimeException: getParameters failed (empty parameters)
                      at android.hardware.Camera.native_getParameters(Native Method)
                      at android.hardware.Camera.getParameters(Camera.java:2117)
                      at com.journeyapps.barcodescanner.camera.CameraManager.setParameters(CameraManager.java:379)
                      at com.journeyapps.barcodescanner.camera.CameraManager.configure(CameraManager.java:159)
                      at com.journeyapps.barcodescanner.camera.CameraInstance$5.run(CameraInstance.java:231)
                      at android.os.Handler.handleCallback(Handler.java:873)
                      at android.os.Handler.dispatchMessage(Handler.java:99)
                      at android.os.Looper.loop(Looper.java:193)
                      at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by rkistner** [comment]
The three errors you reported are likely related to the same underlying issue on this specific device or Android version.

Are these just stack traces in your logs, or is the scanning not working at all?

Do you get the same error when using the [Barcode Scanner](https://play.google.com/store/apps/details?id=com.google.zxing.client.android&hl=en) application?

**Comment by TooLazyy** [comment]
Android 9 same issue. Works on 6 droid.
```
2019-02-20 14:28:54.017 16688-16688/? E/.android.camer: Not starting debugger since process cannot load the jdwp agent.
2019-02-20 14:28:54.068 16688-16688/? E/.android.camer: Invalid ID 0x00000000.
2019-02-20 14:28:54.085 16688-16688/? E/.android.camer: Invalid ID 0x00000000.
2019-02-20 14:28:54.089 16688-16688/? E/.android.camer: No package ID 10 found for ID 0x100d0033.
2019-02-20 14:28:54.089 16688-16688/? E/.android.camer: No package ID 10 found for ID 0x100d0017.
2019-02-20 14:28:54.089 16688-16688/? E/.android.camer: Invalid ID 0x00000000.
2019-02-20 14:28:54.093 16688-16688/? E/.android.camer: Invalid ID 0x00000000.
2019-02-20 14:28:54.096 16688-16688/? E/.android.camer: No package ID 10 found for ID 0x100d0051.
2019-02-20 14:28:54.096 16688-16688/? E/.android.camer: No package ID 10 found for ID 0x100d0047.
2019-02-20 14:28:54.096 16688-16688/? E/.android.camer: Invalid ID 0x00000000.
```

**Comment by rkistner** [comment]
Works on other Android devices I've tested. If you still run into this issue with the latest version, open another issue using the template.

**Comment by sunzc1125** [comment]
I don't confirm if this bug related to zxing bdCode.
