### ISSUE TITLE
In Android API 21 (Lollipop) it is crashing when scanning the QR code

### ISSUE THREAD

**Issue by usmanrana07** [journeyapps/zxing-android-embedded#482]
In Android API 21 (Lollipop) it is crashing when scanning the QR code and giving following Logs:

```
java.lang.NoSuchMethodError: No interface method sort(Ljava/util/Comparator;)V in class Ljava/util/List; or its super classes (declaration of 'java.util.List' appears in /system/framework/core-libart.jar)
        at com.google.zxing.qrcode.detector.FinderPatternFinder.selectBestPatterns(FinderPatternFinder.java:616)
        at com.google.zxing.qrcode.detector.FinderPatternFinder.find(FinderPatternFinder.java:164)
        at com.google.zxing.qrcode.detector.Detector.detect(Detector.java:81)
        at com.google.zxing.qrcode.QRCodeReader.decode(QRCodeReader.java:77)
        at com.google.zxing.MultiFormatReader.decodeInternal(MultiFormatReader.java:173)
        at com.google.zxing.MultiFormatReader.decodeWithState(MultiFormatReader.java:87)
        at com.journeyapps.barcodescanner.Decoder.decode(Decoder.java:75)
        at com.journeyapps.barcodescanner.Decoder.decode(Decoder.java:49)
        at com.journeyapps.barcodescanner.DecoderThread.decode(DecoderThread.java:146)
        at com.journeyapps.barcodescanner.DecoderThread.access$000(DecoderThread.java:22)
        at com.journeyapps.barcodescanner.DecoderThread$1.handleMessage(DecoderThread.java:38)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:145)
        at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by htchaan** [comment]
with reference to zxing/zxing/pull/1180:
```gradle
    implementation('com.journeyapps:zxing-android-embedded:3.6.0') { transitive = false }
    implementation 'com.google.zxing:core:3.3.3' 
```

**Comment by rkistner** [comment]
minSdkVersion is now 24. To support older SDK versions, you'll need to downgrade zxing:core, and even then there may be incompatibilities.
