### ISSUE TITLE
CODE_93 is not suppoted at encode method in MultiformatWriter.

### ISSUE THREAD

**Issue by epmau** [journeyapps/zxing-android-embedded#52]
Hi,

Does this module support CODE_93 format for encoding?
Because the following error occurred when I called the following method.

[my code]
        MultiFormatWriter writer=new MultiFormatWriter();
        BitMatrix result = writer.encode(contents, format, Width, Height, hints);

[result]
STACK_TRACE=java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=49374, result=-1, data=Intent { act=com.google.zxing.client.android.SCAN flg=0x80000 (has extras) }} to activity {com.myapp.mytestapp/com.myapp.mytestapp.Barcode.BarcodeInitialRegistSubActivity}: java.lang.IllegalArgumentException: No encoder available for format CODE_93
at android.app.ActivityThread.deliverResults(ActivityThread.java:3432)
at android.app.ActivityThread.handleSendResult(ActivityThread.java:3475)
at android.app.ActivityThread.access$1100(ActivityThread.java:169)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1326)
at android.os.Handler.dispatchMessage(Handler.java:99)
at android.os.Looper.loop(Looper.java:137)
at android.app.ActivityThread.main(ActivityThread.java:5323)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:511)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:974)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:741)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.IllegalArgumentException: No encoder available for format CODE_93
at com.google.zxing.MultiFormatWriter.encode(MultiFormatWriter.java:92)
at com.myapp.common.barcodes.Barcodes.encodeAsBitmap(Barcodes.java:25)
at com.myapp.mytestapp.Barcode.BarcodeInitialRegistSubActivity.onActivityResult(BarcodeInitialRegistSubActivity.java:129)
at android.app.Activity.dispatchActivityResult(Activity.java:5293)
at android.app.ActivityThread.deliverResults(ActivityThread.java:3428)

Regards,
epmau.

**Comment by rkistner** [comment]
This Android library does not support writing at all currently - that is handled directly by the zxing:core lib.

You can see here that it does not currently support Code_93: 
https://github.com/zxing/zxing/blob/master/core/src/main/java/com/google/zxing/MultiFormatWriter.java
https://github.com/zxing/zxing/tree/master/core/src/main/java/com/google/zxing/oned

I'm guessing it should not be too hard to add support for it though. You can file an issue or pull request there.
