### ISSUE TITLE
Issue crash

### ISSUE THREAD

**Issue by htachoires** [journeyapps/zxing-android-embedded#536]
Hello, while using your library, the version 4.1.0 of com.journeyapps:zxing-android-embedded caused me an exeption, to see if it was my fault i have tried to use the version 3.6.0 and it works. I don't know if it's my config or your code but here is the Exeption. Thanks.

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: ddns.ms.dodgeman.testscan, PID: 20119
    java.lang.BootstrapMethodError: Exception from call site #4 bootstrap method
        at com.journeyapps.barcodescanner.CaptureManager.<init>(CaptureManager.java:130)
        at com.journeyapps.barcodescanner.CaptureActivity.onCreate(CaptureActivity.java:23)
        at android.app.Activity.performCreate(Activity.java:7327)
        at android.app.Activity.performCreate(Activity.java:7318)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3094)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3257)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7050)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)
     Caused by: java.lang.ClassCastException: Bootstrap method returned null
        at com.journeyapps.barcodescanner.CaptureManager.<init>(CaptureManager.java:130) 
        at com.journeyapps.barcodescanner.CaptureActivity.onCreate(CaptureActivity.java:23) 
        at android.app.Activity.performCreate(Activity.java:7327) 
        at android.app.Activity.performCreate(Activity.java:7318) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3094) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3257) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1948) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7050) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:965)

**Comment by rkistner** [comment]
Java 8 language features are used in version 4.x. Try enabling Java 8 compatibility as documented here:
https://developer.android.com/studio/write/java8-support

**Comment by htachoires** [comment]
Thanks, it's now working !
