### ISSUE TITLE
Unmarshalling error

### ISSUE THREAD

**Issue by blennerSilva** [journeyapps/zxing-android-embedded#607]
implementation('com.journeyapps:zxing-android-embedded:4.1.0') { transitive = false }

im using the lib above

ever since android 11 was released this error started to happen 

it happens evarytime um starting the intergator

ERROR 

    Caused by: java.lang.RuntimeException: Parcel android.os.Parcel@a87cb27: Unmarshalling unknown type code 3145778 at offset 604

**Comment by blennerSilva** [comment]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.solution.evamobilesesnew, PID: 2280
    java.lang.RuntimeException: Unable to stop activity {com.solution.evamobilesesnew/com.solution.evamobilero.ui.activty.ConfirmeSerialActivity}: java.lang.RuntimeException: Parcel android.os.Parcel@a87cb27: Unmarshalling unknown type code 3145778 at offset 604
        at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:5306)
        at android.app.ActivityThread.performStopActivityInner(ActivityThread.java:5271)
        at android.app.ActivityThread.handleStopActivity(ActivityThread.java:5351)
        at android.app.servertransaction.StopActivityItem.execute(StopActivityItem.java:40)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2278)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:246)
        at android.app.ActivityThread.main(ActivityThread.java:8429)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:596)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
     Caused by: java.lang.RuntimeException: Parcel android.os.Parcel@a87cb27: Unmarshalling unknown type code 3145778 at offset 604
        at android.os.Parcel.readValue(Parcel.java:3265)
        at android.os.Parcel.readArrayMapInternal(Parcel.java:3579)
        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:292)
        at android.os.BaseBundle.unparcel(BaseBundle.java:236)
        at android.os.BaseBundle.containsKey(BaseBundle.java:516)
        at android.content.Intent.hasExtra(Intent.java:8692)
        at android.app.Activity.onStop(Activity.java:2648)
        at androidx.fragment.app.FragmentActivity.onStop(FragmentActivity.java:559)
        at androidx.appcompat.app.AppCompatActivity.onStop(AppCompatActivity.java:207)
        at android.app.Instrumentation.callActivityOnStop(Instrumentation.java:1476)
        at android.app.Activity.performStop(Activity.java:8402)
        at android.app.ActivityThread.callActivityOnStop(ActivityThread.java:5298)

**Comment by rkistner** [comment]
This library does not use Parcel directly. Are you sure it's related to this library, and not something else in your app?

If you are sure it's related to this library, we'd need a small project that reproduces the issue.

**Comment by blennerSilva** [comment]
i tested on your code and it reproduces de same error
