### ISSUE TITLE
ResourceNotFound Exception

### ISSUE THREAD

**Issue by githubashutoshsoni** [journeyapps/zxing-android-embedded#608]
#### Description of the problem:

After Scanning an item. the results come in OnActivityResult. when on doing result.content. the app crashed. I believe. 

**Which library version are you using?** E.g. 3.2.0.
Library version 4.1.0
**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**
Acer One 7 4G Android version 8.1
**Does the same happen on other devices or an emulator?**
sometimes. 
**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**
NO
**In the case of an error do you have a stack trace or adb logs?**

    android.content.res.Resources$NotFoundException: File res/raw/zxing_beep.ogg from drawable resource ID #0x7f100000
        at android.content.res.ResourcesImpl.openRawResourceFd(ResourcesImpl.java:321)
        at android.content.res.Resources.openRawResourceFd(Resources.java:1293)
        at com.google.zxing.client.android.BeepManager.playBeepSound(BeepManager.java:116)
        at com.google.zxing.client.android.BeepManager.playBeepSoundAndVibrate(BeepManager.java:84)
        at com.journeyapps.barcodescanner.CaptureManager$1.barcodeResult(CaptureManager.java:80)
        at com.journeyapps.barcodescanner.DecoratedBarcodeView$WrappedCallback.barcodeResult(DecoratedBarcodeView.java:50)
        at com.journeyapps.barcodescanner.BarcodeView$1.handleMessage(BarcodeView.java:52)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6523)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)
     Caused by: java.io.FileNotFoundException: This file can not be opened as a file descriptor; it is probably compressed
        at android.content.res.AssetManager.openNonAssetFdNative(Native Method)
        at android.content.res.AssetManager.openNonAssetFd(AssetManager.java:487)
        at android.content.res.ResourcesImpl.openRawResourceFd(ResourcesImpl.java:319)
        at android.content.res.Resources.openRawResourceFd(Resources.java:1293) 
        at com.google.zxing.client.android.BeepManager.playBeepSound(BeepManager.java:116) 
        at com.google.zxing.client.android.BeepManager.playBeepSoundAndVibrate(BeepManager.java:84) 
        at com.journeyapps.barcodescanner.CaptureManager$1.barcodeResult(CaptureManager.java:80) 
        at com.journeyapps.barcodescanner.DecoratedBarcodeView$WrappedCallback.barcodeResult(DecoratedBarcodeView.java:50) 
        at com.journeyapps.barcodescanner.BarcodeView$1.handleMessage(BarcodeView.java:52) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6523) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:857)

**Comment by craz131415** [comment]
I have the same problem

**Comment by githubashutoshsoni** [comment]
I got it fixed by removing that sound image when initiating the scanner. hope it fixes for you too.
