### ISSUE TITLE
setPreviewTexture failed

### ISSUE THREAD

**Issue by fahimk** [journeyapps/zxing-android-embedded#62]
I'm seeing this exception when rotating the device

```java
    java.io.IOException: setPreviewTexture failed
            at android.hardware.Camera.setPreviewSurface(Native Method)
            at android.hardware.Camera.setPreviewDisplay(Camera.java:629)
            at com.journeyapps.barcodescanner.camera.CameraManager.setPreviewDisplay(CameraManager.java:146)
            at com.journeyapps.barcodescanner.camera.CameraInstance$5.run(CameraInstance.java:187)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:148)
            at android.os.HandlerThread.run(HandlerThread.java:61)
```

Here is my xml:

    <FrameLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:foreground="@drawable/header_shadow">

        <com.journeyapps.barcodescanner.BarcodeView
            android:id="@+id/barcode_view"
            android:layout_width="match_parent"
            android:layout_height="match_parent"/>

        <com.jet.jet.libraries.barcode.MyViewFinderView
            android:id="@+id/barcode_view_finder"
            android:layout_width="match_parent"
            android:layout_height="match_parent" />
    </FrameLayout>

**Comment by fahimk** [comment]
Seeing this error sometimes on orientation change too:

```java
    java.lang.RuntimeException: getParameters failed (empty parameters)
            at android.hardware.Camera.native_getParameters(Native Method)
            at android.hardware.Camera.getParameters(Camera.java:1890)
            at com.journeyapps.barcodescanner.camera.CameraManager.setParameters(CameraManager.java:353)
            at com.journeyapps.barcodescanner.camera.CameraManager.configure(CameraManager.java:139)
            at com.journeyapps.barcodescanner.camera.CameraInstance$4.run(CameraInstance.java:171)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:148)
            at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by rkistner** [comment]
Can you please give me the following info? It will help with diagnosing the issue.

* Which version of the library are you using? (e.g. 3.0.0)
* Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)
* Does the same happen on other devices or an emulator?
* Can you reproduce the error in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?

**Comment by fahimk** [comment]
* compile 'com.journeyapps:zxing-android-embedded:3.0.1@aar'
  compile 'com.google.zxing:core:3.2.0'
* nexus 5 android m
* When I use the "1D ANY ORIENTATION" example, and I rotate the device a few times, I get: "Sorry, the Android camera encountered a problem. You may need to restart the device."

**Comment by rkistner** [comment]
This could be related to something on Android M - I've never tested on that.

Are you aware of any other apps that handle orientation changes correctly on your phone? (I don't know of many that actually support changing the orientation)

**Comment by fahimk** [comment]
@rkistner I changed my app to support portrait-only for the barcode scanner. I'm seeing this issue in official release of Android M that came out yesterday:

```java
E/CameraInstance: Failed to configure camera
E/CameraInstance: java.lang.NullPointerException: Attempt to invoke virtual method 'android.hardware.Camera$Parameters android.hardware.Camera.getParameters()' on a null object reference
E/CameraInstance:     at com.journeyapps.barcodescanner.camera.CameraManager.setParameters(CameraManager.java:359)
E/CameraInstance:     at com.journeyapps.barcodescanner.camera.CameraManager.configure(CameraManager.java:139)
E/CameraInstance:     at com.journeyapps.barcodescanner.camera.CameraInstance$4.run(CameraInstance.java:171)
E/CameraInstance:     at android.os.Handler.handleCallback(Handler.java:739)
E/CameraInstance:     at android.os.Handler.dispatchMessage(Handler.java:95)
E/CameraInstance:     at android.os.Looper.loop(Looper.java:148)
E/CameraInstance:     at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by rkistner** [comment]
Duplicated by #89.
