### ISSUE TITLE
Error Scan 

### ISSUE THREAD

**Issue by davideloddeDev** [journeyapps/zxing-android-embedded#643]
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.nuboo.hekolodelivery, PID: 20456
    java.lang.NoClassDefFoundError: android.media.AudioAttributes$Builder
        at com.google.zxing.client.android.BeepManager.playBeepSound(BeepManager.java:97)
        at com.google.zxing.client.android.BeepManager.playBeepSoundAndVibrate(BeepManager.java:84)
        at com.journeyapps.barcodescanner.CaptureManager$1.barcodeResult(CaptureManager.java:80)
        at com.journeyapps.barcodescanner.DecoratedBarcodeView$WrappedCallback.barcodeResult(DecoratedBarcodeView.java:50)
        at com.journeyapps.barcodescanner.BarcodeView$1.handleMessage(BarcodeView.java:52)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5590)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
        at dalvik.system.NativeStart.main(Native Method)

**Comment by ShivamPokhriyal** [comment]
Getting the same error on crashlytics. 100% on Android 4(4.4.4 and 4.4.2). 
```
Fatal Exception: java.lang.NoClassDefFoundError: android.media.AudioAttributes$Builder
       at com.google.zxing.client.android.BeepManager.playBeepSound(BeepManager.java:97)
       at com.google.zxing.client.android.BeepManager.playBeepSoundAndVibrate(BeepManager.java:84)
       at com.journeyapps.barcodescanner.CaptureManager$1.barcodeResult(CaptureManager.java:80)
       at com.journeyapps.barcodescanner.DecoratedBarcodeView$WrappedCallback.barcodeResult(DecoratedBarcodeView.java:50)
       at com.journeyapps.barcodescanner.BarcodeView$1.handleMessage(BarcodeView.java:52)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5584)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
       at dalvik.system.NativeStart.main(NativeStart.java)
```
