### ISSUE TITLE
Build Error - Multiple dex files define IntentResult;

### ISSUE THREAD

**Issue by abhikmitra** [journeyapps/zxing-android-embedded#66]
I am new to android. So this might be a noob question. I followed the steps in the docs and have added the dependencies. When I try to run my app it fails with the following error 

Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
	C:\Users\abmitra\AppData\Local\Android\sdk\build-tools\21.1.2\dx.bat --dex --output D:\Abhik\Nanodegree\alexandria\app\build\intermediates\dex\debug --input-list=D:\Abhik\Nanodegree\alexandria\app\build\intermediates\tmp\dex\debug\inputList.txt
Error Code:
	2
Output:
	UNEXPECTED TOP-LEVEL EXCEPTION:
	com.android.dex.DexException: Multiple dex files define Lcom/google/zxing/integration/android/IntentResult;
		at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
		at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
		at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
		at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
		at com.android.dx.command.dexer.Main.run(Main.java:246)
		at com.android.dx.command.dexer.Main.main(Main.java:215)
		at com.android.dx.command.Main.main(Main.java:106)

Can you tell me where I am going wrong ?

**Comment by rkistner** [comment]
Did you include the library as a dependency in build.gradle, or copy the entire project? It should work fine if you just use it as a dependency, without copying anything.

**Comment by abhikmitra** [comment]
I just added it as a dependency . I have published 
You can see it here : https://github.com/abhikmitra/Productionizing_Android_Apps/blob/master/alexandria/app/build.gradle#L40 

I have used it here for scanning. 

https://github.com/abhikmitra/Productionizing_Android_Apps/blob/master/alexandria/app/src/main/java/it/jaschke/alexandria/AddBook.java#L104


Any help would be appreciated

**Comment by rkistner** [comment]
The sample you posted works for me (tried the first commit, where it uses this library). This was on Linux, but that shouldn't make a difference.

What I can recommend:
1. Install the latest Android SDK tools (build tools, etc).
2. Clean the project and try again.
