### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by JChrist** [journeyapps/zxing-android-embedded#675]
#### Description of the problem:
There are quite a few crashes reported in Play Store for Android SDKs 8.1, 9, 10 and 11 (at least).
The stacktrace for Android SDK 11 is the following. For other Android versions, it is the same, with line numbers on OS methods changing and always going through RawImageData.java:33:
```
java.lang.ArrayIndexOutOfBoundsException: 
  at java.lang.System.arraycopy (System.java:524)
  at com.journeyapps.barcodescanner.RawImageData.cropAndScale (RawImageData.java:33)
  at com.journeyapps.barcodescanner.SourceData.createSource (SourceData.java:12)
  at com.journeyapps.barcodescanner.DecoderThread.createSource (DecoderThread.java:6)
  at com.journeyapps.barcodescanner.DecoderThread.decode (DecoderThread.java:9)
  at com.journeyapps.barcodescanner.DecoderThread.access$000 (DecoderThread.java)
  at com.journeyapps.barcodescanner.DecoderThread$1.handleMessage (DecoderThread.java:12)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:236)
  at android.os.HandlerThread.run (HandlerThread.java:67)
```

**Which library version are you using?** E.g. 3.2.0
4.3.0

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
  Android 5.0)**
Spotted on Play Store, sample with the stacktrace is Redmi Note 8T Android 11 (SDK 30).
There are a lot of others as well, such as Redmi 6 Android 9 (SDK 28), etc

**Does the same happen on other devices or an emulator?**
On devices.

**Can you reproduce the issue in the sample project included with the library? If not, can you
  provide your own sample project or sample code that produces this error?**
Unfortunately not, since I'm reporting the crashes collected by Play Store.

**In the case of an error do you have a stack trace or adb logs?**
For Android 11:
```
java.lang.ArrayIndexOutOfBoundsException: 
  at java.lang.System.arraycopy (System.java:524)
  at com.journeyapps.barcodescanner.RawImageData.cropAndScale (RawImageData.java:33)
  at com.journeyapps.barcodescanner.SourceData.createSource (SourceData.java:12)
  at com.journeyapps.barcodescanner.DecoderThread.createSource (DecoderThread.java:6)
  at com.journeyapps.barcodescanner.DecoderThread.decode (DecoderThread.java:9)
  at com.journeyapps.barcodescanner.DecoderThread.access$000 (DecoderThread.java)
  at com.journeyapps.barcodescanner.DecoderThread$1.handleMessage (DecoderThread.java:12)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:236)
  at android.os.HandlerThread.run (HandlerThread.java:67)
```

**Comment by lgawin-ynd** [comment]
Just got quite similar error:

```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: src.length=307200 srcPos=306792 dst.length=331776 dstPos=165312 length=576
       at java.lang.System.arraycopy(System.java)
       at com.journeyapps.barcodescanner.RawImageData.cropAndScale(RawImageData.java:43)
       at com.journeyapps.barcodescanner.SourceData.createSource(SourceData.java:125)
       at com.journeyapps.barcodescanner.DecoderThread.createSource(DecoderThread.java:135)
       at com.journeyapps.barcodescanner.DecoderThread.decode(DecoderThread.java:143)
       at com.journeyapps.barcodescanner.DecoderThread.access$000(DecoderThread.java:22)
       at com.journeyapps.barcodescanner.DecoderThread$1.handleMessage(DecoderThread.java:38)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at android.os.Looper.loop(Looper.java:154)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Which library version are you using? E.g. 3.2.0**
3.4.1

**Which phone/tablet are you using, and which Android version does it run? (e.g. Samsung Galaxy S5,
Android 5.0)**
PAX A920 (smart POS device) running Android 7.1.2

**Comment by SayokMajumder** [comment]
We are also facing the same issue:

Lib Version:
zxing_embedded_version = "4.3.0"
zxing_core_version = "3.3.3"

Device: 
OnePlus Nord CE 2 Lite 5G

OS Version: 
12

Log:

```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: src.length=1555200 srcPos=1555303 dst.length=724546 dstPos=572470 length=874
       at java.lang.System.arraycopy(System.java:522)
       at com.journeyapps.barcodescanner.RawImageData.cropAndScale(RawImageData.java:214)
       at com.journeyapps.barcodescanner.SourceData.createSource(SourceData.java:214)
       at com.journeyapps.barcodescanner.DecoderThread.createSource(DecoderThread.java:214)
       at com.journeyapps.barcodescanner.DecoderThread.decode(DecoderThread.java:214)
       at com.journeyapps.barcodescanner.DecoderThread.access$000(DecoderThread.java:214)
       at com.journeyapps.barcodescanner.DecoderThread$1.handleMessage(DecoderThread.java:214)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loopOnce(Looper.java:238)
       at android.os.Looper.loop(Looper.java:349)
       at android.os.HandlerThread.run(HandlerThread.java:67) 
```

**Comment by shanky367** [comment]
I also faced the same issue while using zxing lib.
**Lib Version:**
_zxing_embedded_version = "4.3.0"
zxing_core_version = "3.3.3"_

**Device:**
OnePlus Nord CE 2 Lite 5G
**OS Version:**
12

Log:
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: src.length=1555200 srcPos=1555303 dst.length=724546 dstPos=572470 length=874
       at java.lang.System.arraycopy(System.java:522)
       at com.journeyapps.barcodescanner.RawImageData.cropAndScale(RawImageData.java:214)
       at com.journeyapps.barcodescanner.SourceData.createSource(SourceData.java:214)
       at com.journeyapps.barcodescanner.DecoderThread.createSource(DecoderThread.java:214)
       at com.journeyapps.barcodescanner.DecoderThread.decode(DecoderThread.java:214)
       at com.journeyapps.barcodescanner.DecoderThread.access$000(DecoderThread.java:214)
       at com.journeyapps.barcodescanner.DecoderThread$1.handleMessage(DecoderThread.java:214)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loopOnce(Looper.java:238)
       at android.os.Looper.loop(Looper.java:349)
       at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by Ezyger** [comment]
Same problem over here.

**Lib Version:**
zxing_embedded_version = "4.3.0"
zxing_core_version = "3.3.0"

**Device:**
OS Version: 10

Motorola: (46%)
Moto G7 Play (42%)
Moto G7 Power (3%)
Moto G8 (<1%)

Xiaomi: (40%)
Redmi Note 8 (39%)
MI 8 Lite (1%)

LGE K22 (13%)

Samsung (<1%)
Galaxy M52 5G 
Galaxy A20s (<1%)


Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: src.length=768000 srcPos=768015 dst.length=147294 dstPos=74816 length=1169
       at java.lang.System.arraycopy(System.java:527)
       at com.journeyapps.barcodescanner.RawImageData.cropAndScale(RawImageData.java:43)
       at com.journeyapps.barcodescanner.SourceData.createSource(SourceData.java:125)
       at com.journeyapps.barcodescanner.DecoderThread.createSource(DecoderThread.java:135)
       at com.journeyapps.barcodescanner.DecoderThread.decode(DecoderThread.java:143)
       at com.journeyapps.barcodescanner.DecoderThread.access$000(DecoderThread.java:22)
       at com.journeyapps.barcodescanner.DecoderThread$1.handleMessage(DecoderThread.java:38)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:225)
       at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by JanMisker** [comment]
We experience the same, unfortunately not on our own test devices but we do see crash reports with these logs in the PlayStore :(. 
Does anyone have a reproducible case for it? Or found a workaround?

**Comment by grzesiek2010** [comment]
Hi I'm Grzegorz from [ODK Collect](https://github.com/getodk/collect)
I've just spotted a similar crash report in our app. There is just one instance of it:
![image](https://user-images.githubusercontent.com/3276264/228968796-fd264772-c6bb-4d3b-822c-2aad82df269c.png)

and here is the stacktrace:

```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: src.length=495616 srcPos=495020 dst.length=746496 dstPos=151200 length=864
       at java.lang.System.arraycopy(System.java:527)
       at com.journeyapps.barcodescanner.RawImageData.cropAndScale(RawImageData.java:43)
       at com.journeyapps.barcodescanner.SourceData.createSource(SourceData.java:125)
       at com.journeyapps.barcodescanner.DecoderThread.createSource(DecoderThread.java:135)
       at com.journeyapps.barcodescanner.DecoderThread.decode(DecoderThread.java:143)
       at com.journeyapps.barcodescanner.DecoderThread.access$000(DecoderThread.java:22)
       at com.journeyapps.barcodescanner.DecoderThread$1.handleMessage(DecoderThread.java:38)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:251)
       at android.os.HandlerThread.run(HandlerThread.java:67)
```

We use the newest v4.3.0

**Comment by madhumitha998** [comment]
> We experience the same, unfortunately not on our own test devices but we do see crash reports with these logs in the PlayStore :(. Does anyone have a reproducible case for it? Or found a workaround?

Same, seeing these errors on sentry.

**Comment by Hamoda96** [comment]
have the same problem 

Log :
       
       Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: src.length=495616 srcPos=495020 dst.length=746496 dstPos=151200 length=864
       at java.lang.System.arraycopy(System.java:527)
       at com.journeyapps.barcodescanner.RawImageData.cropAndScale(RawImageData.java:43)
       at com.journeyapps.barcodescanner.SourceData.createSource(SourceData.java:125)
       at com.journeyapps.barcodescanner.DecoderThread.createSource(DecoderThread.java:135)
       at com.journeyapps.barcodescanner.DecoderThread.decode(DecoderThread.java:143)
       at com.journeyapps.barcodescanner.DecoderThread.access$000(DecoderThread.java:22)
       at com.journeyapps.barcodescanner.DecoderThread$1.handleMessage(DecoderThread.java:38)
       at android.os.Handler.dispatchMessage(Handler.java:103)
       at android.os.Looper.loop(Looper.java:251)
       at android.os.HandlerThread.run(HandlerThread.java:67)
       
Mobile info :

![Screenshot from 2024-02-19 01-20-41](https://github.com/journeyapps/zxing-android-embedded/assets/31393608/a66557b2-3f52-4086-80df-b6d008cb299c)

what is the soluation for this crash ?

**Comment by dpatel-jac** [comment]
have the same problem

Log :

  `Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: src.length=1036800 srcPos=1035840 dst.length=1183744 dstPos=1173952 length=1088
         at java.lang.System.arraycopy(System.java:527)
         at com.journeyapps.barcodescanner.RawImageData.cropAndScale(RawImageData.java:32)
         at com.journeyapps.barcodescanner.SourceData.createSource(SourceData.java:12)
         at com.journeyapps.barcodescanner.DecoderThread.createSource(DecoderThread.java:6)
         at com.journeyapps.barcodescanner.DecoderThread.decode(DecoderThread.java:9)
         at com.journeyapps.barcodescanner.DecoderThread.access$000(DecoderThread.java)
         at com.journeyapps.barcodescanner.DecoderThread$1.handleMessage(DecoderThread.java:12)
         at android.os.Handler.dispatchMessage(Handler.java:102)
         at android.os.Looper.loopOnce(Looper.java:230)
         at android.os.Looper.loop(Looper.java:319)
         at android.os.HandlerThread.run(HandlerThread.java:67)`
         
         
Device info :

<img width="675" alt="Screenshot 2024-09-20 at 12 34 16 PM" src="https://github.com/user-attachments/assets/86230a17-2aaf-4f2d-9e08-3a09dea9cc7b">


What is resolution this crash?
