### ISSUE TITLE
on Android 6 falls

### ISSUE THREAD

**Issue by maratische** [journeyapps/zxing-android-embedded#95]
android.hardware.Camera is depricated..

Failed to open camera
                                                                             java.lang.RuntimeException: Fail to connect to camera service
                                                                                 at android.hardware.Camera.<init>(Camera.java:495)
                                                                                 at android.hardware.Camera.open(Camera.java:341)
                                                                                 at com.google.zxing.client.android.camera.open.OpenCameraInterface.open(OpenCameraInterface.java:83)
                                                                                 at com.journeyapps.barcodescanner.camera.CameraManager.open(CameraManager.java:121)
                                                                                 at com.journeyapps.barcodescanner.camera.CameraInstance$3.run(CameraInstance.java:158)
                                                                                 at android.os.Handler.handleCallback(Handler.java:739)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                 at android.os.Looper.loop(Looper.java:148)
                                                                                 at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by rkistner** [comment]
Check if this helps:
https://github.com/journeyapps/zxing-android-embedded/issues/89#issuecomment-148148907

**Comment by rkistner** [comment]
Fixed in 3.1.0.
